// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quizzohbjhbjvnwdcopt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1aXp6b2hiamhianZud2Rjb3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNjgzMTksImV4cCI6MjA5MTY0NDMxOX0.znbVaN6n7be9XKcER_BiNnyB1-qqlPvwK7aRhMZWFnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});